### ISSUE TITLE
Mission fonts

### ISSUE THREAD

**Issue by digitalmaster** [exponent/vector-icons#3]
I've noticed that a lot of the fonts listed in the direct seem to be missing. For example when it try to render `chevron-right` i get an `?` and an "Invalid Prop name" console error.

---Console Error----
Warning: Failed prop type: Invalid prop `name` of value `chevron-left` supplied to `Icon`, expected one of ["ios-add","ios-add-circle","ios-add-circle-outline","ios-add-outline","ios-alarm","ios-alarm-outline","ios-albums","ios-albums-outline","ios-alert","ios-alert-outline","ios-american-football","ios-american-football-outline","ios-analytics","ios-analytics-outline","ios-aperture","ios-aperture-outline","ios-apps","ios-apps-outline","ios-appstore",......

Am I missing step?

**Comment by brentvatne** [comment]
maybe you're not importing the correct font name - for example, this will work because material icons has chevron-right:

```
import { MaterialIcons } from '@exponent/vector-icons';

// later on
<MaterialIcons name="chevron-right" />
```

**Comment by digitalmaster** [comment]
Ahhh this makes sense. Thanks a lot.
