### ISSUE TITLE
MaterialCommunityIcons don't exist

### ISSUE THREAD

**Issue by Nickman87** [exponent/vector-icons#4]
I'm just starting out with exponent and immediately ran into an issue integrating the react-native-elements library as apparently they added a new icon list today "MaterialCommunityIcons": https://github.com/react-native-community/react-native-elements/commit/2572af468019d7ee192ac084b6f215690a9e28ea

Reverting to version 0.9.0 works without a problem.

Still experimenting but everything is working great for now, great work!

**Comment by brentvatne** [comment]
thanks! I need to add this to the lib, will do

**Comment by brentvatne** [comment]
added this now, should work if you update to `@exponent/vector-icons` `~4.0.0`
