### ISSUE TITLE
Unable to load icons in a CRNA app

### ISSUE THREAD

**Issue by cheald** [exponent/vector-icons#6]
I've just created a create-react-native-app, and I'm attempting to set up react-native-material-ui with it. I installed @expo/vector-icons, but attempting to use it produces a load error:

    import { MaterialIcons } from '@expo/vector-icons/MaterialIcons'

    3:24:12 PM: (node:19593) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12249): UnableToResolveError: Unable to resolve module ./fonts/MaterialIcons.ttf from /home/chris/projects/wendling/node_modules/@expo/vector-icons/MaterialIcons.js: Directory /home/chris/projects/wendling/node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf doesn't exist

But it definitely exists:

    $ file /home/chris/projects/wendling/node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf
    /home/chris/projects/wendling/node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf: TrueType font data

I'm just dipping my toes into React Native and Expo so it's possible this is just newbie error, but I'm at a loss to explain what. Any pointers?

**Comment by fson** [comment]
@cheald I think the import line needs to be like this instead:
```
import { MaterialIcons } from '@expo/vector-icons'
```

**Comment by cheald** [comment]
Sorry, the import line was an (incorrect) attempt at a minimal reproduction, but it's not the issue. In this case I'm attempting:

    import { Card } from 'react-native-material-ui';

Which at some point attempts to import MaterialIcons, which then fails to load.

![Error screenshot](http://i.imgur.com/f7On3P7.png)

The complete failing App.js is:

```js
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Card } from 'react-native-material-ui';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

and package.json:

```
{
  "name": "wendling",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "0.0.18",
    "jest-expo": "^0.2.1",
    "react-test-renderer": "~15.4.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^4.0.0",
    "expo": "14.0.2",
    "react": "~15.4.0",
    "react-native": "0.41.2",
    "react-native-material-ui": "^1.8.0"
  }
}
```

The same import works just fine in a non-Expo react native app.

**Comment by brentvatne** [comment]
Hello @cheald! Same issue as described here: https://github.com/react-community/create-react-native-app/issues/53

It works now if you create a new project, or you can modify your app.json to add this: https://github.com/exponent/elements-example-crna/blob/master/app.json#L4-L6

Hope that helps! If it solves the problem, feel free to close this issue

**Comment by cheald** [comment]
Fantastic, that did it. Sorry for the noise!

**Comment by khjoony** [comment]
import { Ionicons } from '@expo/vector-icons'; instead of.. import Ionicons from 'react-native-vector-icons/Ionicons';.

**Comment by brentvatne** [comment]
@khjoony - both should work

**Comment by latelt-j** [comment]
Hey, if someone need to import "Material Icons" to work with a library through Expo you can use this code:

`  
    state = {
      readyFlag: false
    };
    async componentWillMount() {
      await Expo.Font.loadAsync({
        'Material Icons': require('@expo/vector-icons/fonts/MaterialIcons.ttf'),
      });
      this.setState({ readyFlag: true });
    }
`
